name: "NAgent Bot"
version: "1.0.0"
slug: "nagent_bot"
description: "LLM-Driven Personal Assistant Bot with Gmail and Calendar integration"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
boot: auto
init: false
options:
  telegram_bot_token: ""
  telegram_chat_id: ""
  huggingface_token: ""
  google_credentials_base64: ""
  log_level: "ERROR"
schema:
  telegram_bot_token: str
  telegram_chat_id: str
  huggingface_token: str
  google_credentials_base64: str
  log_level: list(DEBUG|INFO|WARNING|ERROR)?
hassio_api: true
hassio_role: default