# NAgent Bot Configuration

# Bot Mode Configuration
bot:
  # Primary mode: telegram or cli
  mode: "telegram"
  # Enable automatic daily summaries
  auto_daily_summary: false
  # Daily summary time (if enabled)
  daily_time: "09:00"

# Hugging Face Inference API Configuration
llm:
  # Model settings
  model_name: "google/gemma-2-2b-it"  # Instruction-tuned version
  
  # Inference API settings
  api:
    timeout: 30  # API request timeout in seconds
    max_retries: 3  # Number of retries on failure
    retry_delay: 1  # Delay between retries in seconds
    
  # Generation parameters
  generation:
    max_new_tokens: 1024
    temperature: 0.7
    top_p: 0.9
    top_k: 50
    repetition_penalty: 1.1
    do_sample: true
    # Note: Inference API handles these parameters automatically

# Google API Configuration
google_api:
  credentials_path: "credentials/credentials.json"
  scopes:
    - "https://www.googleapis.com/auth/gmail.readonly"
    - "https://www.googleapis.com/auth/calendar.readonly"

# Agent Configuration
agents:
  gmail:
    max_results: 20
    max_age_hours: 24
  calendar:
    max_results: 20
    
# Response Configuration
response:
  # Max message length for Telegram (characters)
  max_message_length: 4000
  # Truncate long responses
  truncate_long_responses: true

# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/orchestrator.log"